Cervantes.Web/Areas/Workspace/Models/VulnViewModel.cs
using Cervantes.CORE;
using System.Collections.Generic;

namespace Cervantes.Web.Areas.Workspace.Models;

public class VulnViewModel
{
    public Project Project { get; set; }
    public IEnumerable<Vuln> Vulns { get; set; }
}

Cervantes.Web/Areas/Workspace/Controllers/VulnController.cs
using Cervantes.Contracts;
using Cervantes.CORE;
using Cervantes.Web.Areas.Workspace.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using Cervantes.IFR.Jira;
using Cervantes.IFR.Parsers.Burp;
using Cervantes.IFR.Parsers.CSV;
using Cervantes.IFR.Parsers.Nessus;
using Cervantes.IFR.Parsers.Pwndoc;
using CsvHelper;
using CsvHelper.Configuration;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MimeDetective;

namespace Cervantes.Web.Areas.Workspace.Controllers;
[Authorize(Roles = "Admin,SuperUser,User")]
[Area("Workspace")]
public class VulnController : Controller
{
    private IVulnManager vulnManager = null;
    private IProjectManager projectManager = null;
    private ITargetManager targetManager = null;
    private IVulnCategoryManager vulnCategoryManager = null;
    private IVulnNoteManager vulnNoteManager = null;
    private IVulnAttachmentManager vulnAttachmentManager = null;
    private IVulnTargetManager vulnTargetManager = null;
    private IProjectUserManager projectUserManager = null;
    private readonly IHostingEnvironment _appEnvironment;
    private readonly ILogger<VulnController> _logger = null;
    private IJIraService jiraService = null;
    private IJiraManager jiraManager = null;
    private IJiraCommentManager jiraCommentManager = null;
    private IProjectAttachmentManager projectAttachmentManager = null;
    private ICsvParser csvParser = null;
    private IPwndocParser pwndocParser = null;
    private IBurpParser burpParser = null;
    private INessusParser nessusParser = null;
    private ICweManager cweManager = null;
    private IVulnCweManager vulnCweManager = null;

    public VulnController(IVulnManager vulnManager, IProjectManager projectManager, ILogger<VulnController> logger,
        ITargetManager targetManager, IVulnTargetManager vulnTargetManager,
        IVulnCategoryManager vulnCategoryManager, IVulnNoteManager vulnNoteManager,
        IVulnAttachmentManager vulnAttachmentManager, IProjectUserManager projectUserManager, IHostingEnvironment _appEnvironment,
        IJIraService jiraService, IJiraManager jiraManager, IJiraCommentManager jiraCommentManager, IProjectAttachmentManager projectAttachmentManager,
        ICsvParser csvParser, IPwndocParser pwndocParser,IBurpParser burpParser, INessusParser nessusParser, ICweManager cweManager, IVulnCweManager vulnCweManager )
    {
        this.vulnManager = vulnManager;
        this.projectManager = projectManager;
        this.targetManager = targetManager;
        this.vulnCategoryManager = vulnCategoryManager;
        this.vulnAttachmentManager = vulnAttachmentManager;
        this.vulnNoteManager = vulnNoteManager;
        this.vulnTargetManager = vulnTargetManager;
        this.projectUserManager = projectUserManager;
        this._appEnvironment = _appEnvironment;
        _logger = logger;
        this.jiraService = jiraService;
        this.jiraCommentManager = jiraCommentManager;
        this.jiraManager = jiraManager;
        this.projectAttachmentManager = projectAttachmentManager;
        this.csvParser = csvParser;
        this.pwndocParser = pwndocParser;
        this.burpParser = burpParser;
        this.nessusParser = nessusParser;
        this.cweManager = cweManager;
        this.vulnCweManager = vulnCweManager;
    }

    // GET: VulnController
    public ActionResult Index(Guid project)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces",new {area =""});
            }
            var model = new VulnViewModel
            {
                Project = projectManager.GetById(project),
                Vulns = vulnManager.GetAll().Where(x => x.ProjectId == project && x.Template == false).ToList()
            };
            return View(model);
        }
        catch (Exception e)
        {
            _logger.LogError(e, "An error ocurred loading Vuln Workspace Index. Project: {1} User: {2}", project,
                User.FindFirstValue(ClaimTypes.Name));
            return Redirect("/Home/Error");
        }
    }

    // GET: VulnController/Details/5
    public ActionResult Details(Guid project, Guid id)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces",new {area =""});
            }
            
            var result = targetManager.GetAll().Where(x => x.ProjectId == project).Select(e => new VulnCreateViewModel
            {
                TargetId = e.Id,
                TargetName = e.Name
            }).ToList();

            var targets = new List<SelectListItem>();

            foreach (var item in result)
                targets.Add(new SelectListItem {Text = item.TargetName, Value = item.TargetId.ToString()});
            
            var jiraEnabled = jiraService.JiraEnabled();
            if (jiraEnabled == true)
            {
                var vuln = vulnManager.GetById(id);
                
                if (vuln.JiraCreated == true)
                {
                    var jira = jiraManager.GetByVulnId(id);
                    //jiraService.Issue(jira.JiraKey);
                    
                    var model = new VulnDetailsViewModel
                    {
                        Project = projectManager.GetById(project),
                        Vuln = vuln,
                        Notes = vulnNoteManager.GetAll().Where(x => x.VulnId == id),
                        Attachments = vulnAttachmentManager.GetAll().Where(x => x.VulnId == id),
                        Targets = vulnTargetManager.GetAll().Where(x => x.VulnId == id).ToList(),
                        TargetList = targets,
                        JiraEnabled = jiraService.JiraEnabled(),
                        Jira = jira,
                        JiraComments = jiraCommentManager.GetAll().Where(x => x.JiraId == jira.Id).ToList(),
                        Cwe = vulnCweManager.GetAll().Where(x => x.VulnId == id).ToList()
                    };
                    return View(model);
                }
                else
                {

                    var model = new VulnDetailsViewModel
                    {
                        Project = projectManager.GetById(project),
                        Vuln = vuln,
                        Notes = vulnNoteManager.GetAll().Where(x => x.VulnId == id),
                        Attachments = vulnAttachmentManager.GetAll().Where(x => x.VulnId == id),
                        Targets = vulnTargetManager.GetAll().Where(x => x.VulnId == id).ToList(),
                        TargetList = targets,
                        JiraEnabled = jiraService.JiraEnabled(),
                        Cwe = vulnCweManager.GetAll().Where(x => x.VulnId == id).ToList()
                    };
                    return View(model);
                }
            }
            else
            {
                var model = new VulnDetailsViewModel
                {
                    Project = projectManager.GetById(project),
                    Vuln = vulnManager.GetById(id),
                    Notes = vulnNoteManager.GetAll().Where(x => x.VulnId == id),
                    Attachments = vulnAttachmentManager.GetAll().Where(x => x.VulnId == id),
                    Targets = vulnTargetManager.GetAll().Where(x => x.VulnId == id).ToList(),
                    TargetList = targets,
                    JiraEnabled = jiraService.JiraEnabled(),
                    Cwe = vulnCweManager.GetAll().Where(x => x.VulnId == id).ToList()
                };
                return View(model);
            }

            
        }
        catch (Exception e)
        {
            TempData["errorVuln"] = "Error loading vuln!";
            _logger.LogError(e, "An error ocurred loading Vuln Workspace Details.Task: {0} Project: {1} User: {2}", id,
                project, User.FindFirstValue(ClaimTypes.Name));
            return RedirectToAction("Index");
        }
    }

    // GET: VulnController/Create
    public ActionResult Create(Guid project)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces",new {area =""});
            }
            var result = targetManager.GetAll().Where(x => x.ProjectId == project).Select(e => new VulnCreateViewModel
            {
                TargetId = e.Id,
                TargetName = e.Name
            }).ToList();

            var targets = new List<SelectListItem>();

            foreach (var item in result)
                targets.Add(new SelectListItem {Text = item.TargetName, Value = item.TargetId.ToString()});

            /*var result2 = vulnCategoryManager.GetAll().Select(e => new VulnCreateViewModel
            {
                VulnCategoryId = e.Id,
                VulnCategoryName = e.Name
            }).ToList();

            var vulnCat = new List<SelectListItem>();

            foreach (var item in result2)
                vulnCat.Add(new SelectListItem {Text = item.VulnCategoryName, Value = item.VulnCategoryId.ToString()});*/

Cervantes.Web/Views/Vuln/Categories.cshtml
@using Cervantes.CORE
@model IEnumerable<VulnCategory>

@{
    ViewData["Title"] = "Vuln Categories";
}
@{


    if (TempData["createdVulnCategory"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong localize-content>Vuln category created successfully!</strong>

        </div>
    }

    if (TempData["editedVulnCat"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <strong localize-content>Vuln category edited successfully!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }

    

}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 localize-content><i class="fas fa-bug"></i> Vulnerability Categories</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item active">
                        <a asp-controller="Vuln" asp-action="Index" localize-content>Vulnerability</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Categories</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>

<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-body">
            
            <!--Table-->
            <table id="vulnCategories" class="table table-bordered table-hover" width="100%">
                <!--Table head-->
                <thead class="thead-dark">
                <tr>
                    <th localize-content><i class="fas fa-bug"></i> <span localize-content>Name</span></th>
                    <th localize-content><i class="fas fa-align-left"></i> <span localize-content>Description</span></th>
                    <th localize-content><i class="fas fa-project-diagram"></i> <span localize-content>Type</span></th>
                    <th localize-content><i class="fas fa-cog"></i> <span localize-content>Options</span></th>
                </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>

                @foreach (var cat in Model)
                {
                    <tr>
                        <td>@cat.Name</td>
                        <td>@cat.Description</td>
                        <td>@cat.Type</td>
                        @if (User.IsInRole("Admin") || User.IsInRole("SuperUser"))
                        {
                            <td>
                                <a class="btn btn-tool" asp-area="" asp-controller="Vuln" asp-action="EditCategory" asp-route-id="@cat.Id" localize-content>
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a class="btn btn-tool" asp-area="" asp-controller="Vuln" asp-action="DeleteCategory" asp-route-id="@cat.Id" localize-content>
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                        }

                    </tr>
                }

                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
            

        </div>
    </div>
    <a asp-area="" asp-controller="Home" asp-action="Index" class="btn btn-light"><i class="fas fa-arrow-left"></i> <span localize-content>Back</span></a>
            <a asp-area="" asp-controller="Vuln" asp-action="CreateCategory" class="btn btn-dark"><i class="fas fa-project-diagram"></i> <span localize-content>Create</span></a>
</section>
<!-- /.content -->
<!-- /.content-wrapper -->

@section Scripts{
    <script>

    $(document).ready(function () {
        $('#vulnCategories').DataTable({
            "responsive": true
        });
        $('.dataTables_length').addClass('bs-select');
    });


</script>
}

Cervantes.Web/Views/Vuln/CreateCategory.cshtml
@using Cervantes.CORE
@model VulnCategoryViewModel

@{
    ViewData["Title"] = "Create Vuln Category";
}

@{
    if (TempData["errorCreatingVulnCat"] != null)
    {
        <div class="alert alert-danger alert-dismissible">
            <strong localize-content>An error ocurred creating vuln category!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 localize-content><i class="fas fa-bug"></i> <span localize-content>Create Vulnerability Category</span></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-controller="Vuln" asp-action="Index" localize-content>Vulnerability</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Create Category</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>
<!-- Main content -->
<section class="content">
<div class="card">
<div class="card-body">

    <div class="col-md-12">
        <form asp-area="" asp-controller="Vuln" asp-action="CreateCategory" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label" localize-content>Name</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label" localize-content>Description</label>
                <textarea id="descriptionTxt" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" localize-content>Type</label>
                @Html.DropDownListFor(model => model.Type, Html.GetEnumSelectList<VulnCategoryType>(), new {@class = "form-control"})
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <a class="btn btn-light" asp-action="Index" localize-content>Back</a>
                <button type="submit" class="btn btn-dark" localize-content>Create</button>
            </div>

        </form>
    </div>
        
</div>
</div>
</section>

@section Scripts
{
    <script>
    $(document).ready(function() { 
          $('#descriptionTxt').summernote({
          height: 300,
          });
          });
  
        
  
    
    </script>
}

Cervantes.Web/Views/Vuln/Delete.cshtml
@model Cervantes.CORE.Vuln

@{
    ViewData["Title"] = "Delete Vulnerability";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1><i class="fas fa-briefcase"></i> <span localize-content>Delete Vulnerability</span></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-controller="Vuln" asp-action="Index" localize-content>Vulnerability</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Delete</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>

<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-body">
            <h3 localize-content>Are you sure you want to delete this?</h3>

            <div>

                <dl class="row">
                    <dt class="col-sm-2" localize-content>
                        Name
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2" localize-content>
                        Project
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Project.Name)
                    </dd>
                    <dt class="col-sm-2" localize-content>
                        CVSS3 Score
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CVSS3)
                    </dd>
                    <dt class="col-sm-2" localize-content>
                        Risk
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Risk)
                    </dd>
                    <dt class="col-sm-2" localize-content>
                        Status
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    <dt class="col-sm-2" localize-content>
                        Target
                    </dt>
                </dl>

                <form asp-controller="Vuln" asp-action="Delete" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id"/>
                    <a class="btn btn-light" asp-action="Index" localize-content>Back</a>
                    <button type="submit" class="btn btn-outline-danger" localize-content>Delete</button>
                </form>
            </div>
        </div>
    </div>
</section>

Cervantes.Web/Views/Vuln/DeleteCategory.cshtml
@model Cervantes.CORE.VulnCategory

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    if (TempData["errorDeletingVulnCat"] != null)
    {
        <div class="alert alert-danger alert-dismissible">
            <strong localize-content>An error ocurred deleting vuln category!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 localize-content><i class="fas fa-briefcase"></i> Delete Client</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-controller="Client" asp-action="Index" localize-content>Admin</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Vuln</li>
                    <li class="breadcrumb-item active" localize-content>Delete Category</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>

<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-body">
            <h3 localize-content>Are you sure you want to delete this?</h3>

            <div>

                <dl class="row">
                    <dt class="col-sm-2">
                        <strong localize-content>Name</strong>
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        <strong localize-content>Description</strong>
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                </dl>

                <form asp-area="" asp-controller="Vuln" asp-action="DeleteCategory" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="Id"/>
                    <a class="btn btn-light" asp-action="Index" localize-content>Back</a>
                    <button type="submit" class="btn btn-outline-danger" localize-content>Delete</button>
                </form>
            </div>
        </div>
    </div>
</section>

Cervantes.Web/Views/Vuln/EditCategory.cshtml
@using Cervantes.CORE
@model VulnCategoryViewModel

@{
    ViewData["Title"] = "Edit Vuln Category";
}

@{
    if (TempData["errorEditedVulnCat"] != null)
    {
        <div class="alert alert-danger alert-dismissible">
            <strong localize-content>An error ocurred editing vuln category!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 localize-content><i class="fas fa-bug"></i> <span localize-content>Edit Vulnerability Category</span></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-controller="Vuln" asp-action="Index" localize-content>Vulnerability</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Edit Category</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>
<!-- Main content -->
<section class="content">
<div class="card">
<div class="card-body">

    <div class="col-md-12">
        <form asp-area="" asp-controller="Vuln" asp-action="EditCategory" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label" localize-content>Name</label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label" localize-content>Description</label>
                <textarea id="descriptionTxt" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" localize-content>Type</label>
                @Html.DropDownListFor(model => model.Type, Html.GetEnumSelectList<VulnCategoryType>(), new {@class = "form-control"})
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <a class="btn btn-light" asp-action="Index" localize-content>Back</a>
                <button type="submit" class="btn btn-dark" localize-content>Edit</button>
            </div>

        </form>
    </div>
</div>
</div>
</section>

@section Scripts
{
    <script>
    $(document).ready(function() { 
          $('#descriptionTxt').summernote({
          height: 300,
          });
          });
    
    
    </script>
}