Cervantes.Web/Areas/Workspace/Models/ExecutiveSummaryViewModel.cs
using Cervantes.CORE;

namespace Cervantes.Web.Areas.Workspace.Models;

public class ExecutiveSummaryViewModel
{
    public Project Project { get; set; }
    public string ExecutiveSummary { get; set; }
}

Cervantes.Web/Models/ProjectViewModel.cs
using Cervantes.CORE;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Cervantes.Web.Models;

public class ProjectViewModel
{
    /// <summary>
    /// Project Id
    /// </summary>
    ///
    public Guid Id { get; set; }

    /// <summary>
    /// Project Name
    /// </summary>
    [Required]
    public string Name { get; set; }

    /// <summary>
    /// Project Description
    /// </summary>
    [Required]
    public string Description { get; set; }

    /// <summary>
    /// Project Start Date
    /// </summary>
    [Required]
    [DataType(DataType.Date)]
    public DateTime StartDate { get; set; }

    /// <summary>
    /// Project End Date
    /// </summary>
    [Required]
    [DataType(DataType.Date)]
    public DateTime EndDate { get; set; }

    /// <summary>
    /// User who created project
    /// </summary>
    public virtual ApplicationUser User { get; set; }

    /// <summary>
    /// Id user
    /// </summary>
    public string UserId { get; set; }

    /// <summary>
    /// Client asssociated to project
    /// </summary>
    [Required]
    public virtual Client Client { get; set; }

    /// <summary>
    /// Client ID
    /// </summary>
    [Required]
    public Guid ClientId { get; set; }

    /// <summary>
    /// Is project a template
    /// </summary>
    public bool Template { get; set; }

    public IList<SelectListItem> ItemList { get; set; }
    public IList<SelectListItem> StatusList { get; set; }
    public IList<SelectListItem> TypeList { get; set; }

    /// <summary>
    /// Project Status
    /// </summary>
    [Required]
    public ProjectStatus Status { get; set; }

    /// <summary>
    /// Project Type
    /// </summary>
    [Required]
    public ProjectType ProjectType { get; set; }
    
    /// <summary>
    /// Project Language
    /// </summary>
    [Required]
    public Language Language { get; set; }
    
    /// <summary>
    /// Project Score
    /// </summary>
    [Required]
    public Score Score { get; set; }

    [Required]
    public string FindingsId { get; set; }
}

Cervantes.Web/Areas/Workspace/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Web;
using Cervantes.Contracts;
using Cervantes.CORE;
using Cervantes.IFR.Email;
using Cervantes.Web.Areas.Workspace.Models;
using Cervantes.Web.Models;
using Ganss.XSS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;

namespace Cervantes.Web.Areas.Workspace.Controllers;
[Authorize(Roles = "Admin,SuperUser,User")]
[Area("Workspace")]
public class ProjectController: Controller
{
    private readonly ILogger<ProjectController> _logger = null;
    private readonly IHostingEnvironment _appEnvironment;
    private IProjectManager projectManager = null;
    private IClientManager clientManager = null;
    private IProjectUserManager projectUserManager = null;
    private IProjectNoteManager projectNoteManager = null;
    private IProjectAttachmentManager projectAttachmentManager = null;
    private ITargetManager targetManager = null;
    private ITaskManager taskManager = null;
    private IUserManager userManager = null;
    private IVulnManager vulnManager = null;
    private IReportManager reportManager = null;
    private IReportTemplateManager reportTemplateManager = null;
    private IEmailService email = null;

    /// <summary>
    /// ProjectController Constructor
    /// </summary>
    /// <param name="projectManager">ProjectManager</param>
    /// <param name="clientManager">ClientManager</param>
    public ProjectController(IProjectManager projectManager, IClientManager clientManager,
        IProjectUserManager projectUserManager, IProjectNoteManager projectNoteManager,
        IProjectAttachmentManager projectAttachmentManager, ITargetManager targetManager, ITaskManager taskManager,
        IUserManager userManager, IVulnManager vulnManager, IHostingEnvironment _appEnvironment,
        ILogger<ProjectController> logger, IReportManager reportManager, IReportTemplateManager reportTemplateManager,IEmailService email)
    {
        this.projectManager = projectManager;
        this.clientManager = clientManager;
        this.projectUserManager = projectUserManager;
        this.projectNoteManager = projectNoteManager;
        this.projectAttachmentManager = projectAttachmentManager;
        this.targetManager = targetManager;
        this.taskManager = taskManager;
        this.userManager = userManager;
        this.vulnManager = vulnManager;
        this._appEnvironment = _appEnvironment;
        _logger = logger;
        this.reportManager = reportManager;
        this.reportTemplateManager = reportTemplateManager;
        this.email = email;
    }

    public IActionResult ExecutiveSummary(Guid project)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces", new {area = ""});
            }

            var pro = projectManager.GetById(project);
            var model = new ExecutiveSummaryViewModel
            {
                Project = pro,
                ExecutiveSummary = pro.ExecutiveSummary
            };
            

            return View(model);
        }
        catch (Exception ex)
        {
            TempData["errorExecutive"] = "loading project";
            _logger.LogError(ex, "An error ocurred loading Project Executive Summary: {0}. User: {1}", project,
                User.FindFirstValue(ClaimTypes.Name));
            return RedirectToAction("Error", "Home");
        }
        
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult ExecutiveSummary(Guid project, ExecutiveSummaryViewModel model)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces", new {area = ""});
            }

            var sanitizer = new HtmlSanitizer();
            sanitizer.AllowedSchemes.Add("data");
            
            var pro = projectManager.GetById(project);
            pro.ExecutiveSummary = sanitizer.Sanitize(HttpUtility.HtmlDecode(model.ExecutiveSummary));

            projectManager.Context.SaveChanges();
            TempData["executiveSaved"] = "saved";
            _logger.LogInformation("User: {0} Edited a new Executive Summary on Project {1}",
                User.FindFirstValue(ClaimTypes.Name),
                project);
            return RedirectToAction("ExecutiveSummary");
        }
        catch (Exception ex)
        {
            TempData["errorExecutiveSave"] = "loading project";
            _logger.LogError(ex, "An error ocurred loading Project Executive Summary: {0}. User: {1}", project,
                User.FindFirstValue(ClaimTypes.Name));
            return RedirectToAction("ExecutiveSummary");
        }
        
    }
    
     /// <summary>
    /// Methos show project details
    /// </summary>
    /// <param name="id">Project Id</param>
    /// <returns></returns>
    [Authorize(Roles = "Admin,SuperUser,User,Client")]
    public ActionResult Details(Guid project)
    {
        try
        {
            var user = projectUserManager.VerifyUser(project, User.FindFirstValue(ClaimTypes.NameIdentifier));
            if (user == null)
            {
                TempData["userProject"] = "User is not in the project";
                return RedirectToAction("Index", "Workspaces",new {area =""});
            }
            
            var projectDet = projectManager.GetById(project);
            
           
            
            if (projectDet != null)
            {
                
                
                var result = userManager.GetAll().Select(e => new ApplicationUser
                {
                    Id = e.Id,
                    FullName = e.FullName
                }).ToList();

                var users = new List<SelectListItem>();

                foreach (var item in result)
                    users.Add(new SelectListItem {Text = item.FullName, Value = item.Id.ToString()});
                
                var repTemplates2 = reportTemplateManager.GetAll().Where(x => x.Language == projectDet.Language).Select(e => new ReportTemplate
                {
                    Id = e.Id,
                    Name = e.Name,
                }).ToList();

                var liRep2 = new List<SelectListItem>();

                foreach (var item in repTemplates2) liRep2.Add(new SelectListItem {Text = item.Name, Value = item.Id.ToString()});

                var model = new ProjectDetailsViewModel
                {
                    Project = projectDet,
                    ProjectUsers = projectUserManager.GetAll().Where(x => x.ProjectId == project).ToList(),
                    ProjectNotes = projectNoteManager.GetAll().Where(x => x.ProjectId == project),
                    ProjectAttachments = projectAttachmentManager.GetAll().Where(x => x.ProjectId == project),
                    Targets = targetManager.GetAll().Where(x => x.ProjectId == project),
                    Tasks = taskManager.GetAll().Where(x => x.ProjectId == project),
                    Users = users.ToList(),
                    Vulns = vulnManager.GetAll().Where(x => x.ProjectId == project).ToList(),
                    Reports = reportManager.GetAll().Where(x => x.ProjectId == project).ToList(),
                    ReportTemplates = liRep2.ToList()
                };
                return View(model);
            }

            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["errorLoadingProject"] = "loading project";
            _logger.LogError(ex, "An error ocurred loading Project: {0}. User: {1}", project,
                User.FindFirstValue(ClaimTypes.Name));
            return RedirectToAction("Index");
        }
    }
     
     /// <summary>
    /// Method Add user to project
    /// </summary>
    /// <param name="project">Project Id</param>
    /// <param name="user">User Id</param>
    /// <returns></returns>
    [Authorize(Roles = "Admin,SuperUser")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddMember(Guid project, string users)
    {
        try
        {
            if (project != null && users != null)
            {
                var result = projectUserManager.GetAll().Where(x => x.UserId == users && x.ProjectId == project);

                if (result.FirstOrDefault() == null)
                {
                    var user = new ProjectUser
                    {
                        ProjectId = project,
                        UserId = users
                    };
                    projectUserManager.Add(user);
                    projectUserManager.Context.SaveChanges();
                    TempData["addedMember"] = "added";
                    _logger.LogInformation("User: {0} Added new member Member on Project: {2}",
                        User.FindFirstValue(ClaimTypes.Name), project);

                    var userRes = userManager.GetByUserId(user.UserId);
                    var projectRes = projectManager.GetById(user.ProjectId);
                    
                    var to = new List<EmailAddress>();
                    to.Add(new EmailAddress
                    {
                        Address = userRes.Email,
                        Name = userRes.FullName,
                    });

                    StreamReader sr =new StreamReader(_appEnvironment.WebRootPath + "/Resources/Email/AddedToProject.html");

Cervantes.Web/Areas/Workspace/Views/Project/ExecutiveSummary.cshtml
@model ExecutiveSummaryViewModel


@{
    ViewData["Title"] = "Executive Summary";
}

@{
    if (TempData["executiveSaved"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <strong localize-content>Executive Summary saved successfully!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }
    
    if (TempData["errorExecutiveSave"] != null)
    {
        <div class="alert alert-danger alert-dismissible">
            <strong localize-content>An error ocurred saving Executive Summary!</strong>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    }
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 localize-content><i class="fas fa-file-alt"></i> <span localize-content>Executive Summary</span></h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" localize-content>Home</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-area="" asp-controller="Workspaces" asp-action="Index" localize-content>Workspace</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-area="Workspace" asp-controller="Home" asp-action="Index" asp-route-project="@Model.Project.Id" localize-content>@Model.Project.Name</a>
                    </li>
                    <li class="breadcrumb-item" localize-content>
                        <a asp-area="Workspace" asp-controller="Project" asp-action="Details" localize-content>Project</a>
                    </li>
                    <li class="breadcrumb-item active" localize-content>Executive Sumamry</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
    <hr/>
</section>

<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-body">

            <div class="row justify-content-center">
                <div class="col-md-12">
                    <form asp-area="Workspace" asp-controller="Project" asp-action="ExecutiveSummary" method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="ExecutiveSummary" class="control-label" localize-content>Description</label>
                            <textarea id="description" asp-for="ExecutiveSummary" class="form-control" rows="8"></textarea>
                            <span asp-validation-for="ExecutiveSummary" class="text-danger"></span>
                            <button type="submit" class="btn btn-dark" localize-content>Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


</section>


@section Scripts{
    <script>

  $(document).ready(function() {
      $('#description').summernote({
      height: 600,
      });
      });
    

   
         $(document).ready(function () {
  bsCustomFileInput.init();
});

</script>
}